### ISSUE TITLE
mysql2 0.5.2がインストールができない件

### ISSUE THREAD

**Issue by niceonionslice** [niceonionslice/taskleaf-sandbox#2]
メールアドレスとパスワードの組み合わせによる認証機能を作る

**Comment by niceonionslice** [comment]
「What(何を？)」「Why(なぜ？)」「How(どのように？)」

タスク管理システムに認証機能を実装する。

自分のタスクの追加、編集、閲覧、削除を実現するため。
また、他人のタスクについて追加、編集、閲覧、削除ができないようにするため。

アカウント管理機能を追加する。

**Comment by niceonionslice** [comment]
![image](https://user-images.githubusercontent.com/30763221/53696772-d7f27980-3e0d-11e9-84c6-e5f5029273fc.png)

:beginner:

**Comment by niceonionslice** [comment]
データベースでパスワードを保持する場合は直接パスワードを保持せずにダイジェストする。
password NG
password_digest OK

**Comment by niceonionslice** [comment]
![image](https://user-images.githubusercontent.com/30763221/53696968-67e4f300-3e0f-11e9-965b-aa42a458a280.png)

**Comment by niceonionslice** [comment]
Userモデル作成。モデル作成検証
![image](https://user-images.githubusercontent.com/30763221/53697098-02920180-3e11-11e9-9b7f-e9d0bd608af6.png)

⭐️

**Comment by niceonionslice** [comment]
bcryptをgemに追加しようとしてエラーが発生 ⚠️ 
bcryptの最新版 `gem 'bcrypt', '~> 3.1', '>= 3.1.12'`にしたらbundle失敗。
何度か試して失敗したのでとりあえず bundleの保存先のフォルダ事削除したら今度は nokogiで怒られた。

![image](https://user-images.githubusercontent.com/30763221/53697476-d0829e80-3e14-11e9-9c0b-7fae64fba39e.png)

nokogiriについてはこのサイトを参考に対応。
https://qiita.com/dskst/items/b1f073fcffeca3bc9fc6

`brew doctor`そしたらxcodeインストールするように言われたのインストール
`xcode-select --install`

これでbundle installが一応動いた。
エラーになったけど nokogiriはクリアー

**Comment by niceonionslice** [comment]
トラブルは続くよ。:warning:
![image](https://user-images.githubusercontent.com/30763221/53697506-1b041b00-3e15-11e9-8c5d-216fcbef6ac6.png)

Install mysql2 on MacOS Mojave by GitHubGist
https://gist.github.com/fernandoaleman/ee3ac6957c2ba4f7d7d33a251d58b191

**Comment by niceonionslice** [comment]
↑この方法を試してみたけど gemは確かにインストールされたけどbundleの範囲ではまだmysql2はインストールできず。

```
Fetching mysql2 0.5.2
Installing mysql2 0.5.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/ext/mysql2
/Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/bin/ruby -I
/Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0 -r ./siteconf20190304-66736-ex5d51.rb extconf.rb
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
-----
Using mysql_config at /usr/local/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for SSL_MODE_DISABLED in mysql.h... yes
checking for SSL_MODE_PREFERRED in mysql.h... yes
checking for SSL_MODE_REQUIRED in mysql.h... yes
checking for SSL_MODE_VERIFY_CA in mysql.h... yes
checking for SSL_MODE_VERIFY_IDENTITY in mysql.h... yes
checking for MYSQL.net.vio in mysql.h... yes
checking for MYSQL.net.pvio in mysql.h... no
checking for MYSQL_ENABLE_CLEARTEXT_PLUGIN in mysql.h... yes
checking for SERVER_QUERY_NO_GOOD_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_NO_INDEX_USED in mysql.h... yes
checking for SERVER_QUERY_WAS_SLOW in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_ON in mysql.h... yes
checking for MYSQL_OPTION_MULTI_STATEMENTS_OFF in mysql.h... yes
checking for my_bool in mysql.h... no
-----
Don't know how to set rpath on your system, if MySQL libraries are not in path mysql2 may not load
-----
-----
Setting libpath to /usr/local/Cellar/mysql/8.0.15/lib
-----
creating Makefile

current directory: /Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/ext/mysql2
make "DESTDIR=" clean

current directory: /Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/ext/mysql2
make "DESTDIR="
compiling client.c
compiling infile.c
compiling mysql2_ext.c
compiling result.c
compiling statement.c
linking shared-object mysql2/mysql2.bundle
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mysql2.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2 for
inspection.
Results logged to
/Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/vendor/bundle/ruby/2.5.0/extensions/x86_64-darwin-17/2.5.0-static/mysql2-0.5.2/gem_make.out

An error occurred while installing mysql2 (0.5.2), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.5.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mysql2
```

**Comment by niceonionslice** [comment]
Qiitaで同じエラーの方いました。
https://qiita.com/HrsUed/items/ca2e0aee6a2402571cf6
rubygemsの中まで見てる。すげーな。

```
$ brew info openssl
…
  set -gx LDFLAGS "-L/usr/local/opt/openssl/lib"
  set -gx CPPFLAGS "-I/usr/local/opt/openssl/include"
```

gem install mysql2 -v '0.5.2' --source 'https://rubygems.org/' -- --with-cppflags=-I/usr/local/opt/openssl/include --with-ldflags=-L/usr/local/opt/openssl/lib

これでgem インストールできたけど。。。
bundle installするとまだ原因は解消できず。。

なので、 gemディレクトリ事削除
```
$ rm -rf ./vendor/bundle
```
ダメだった。

とりあえず、　opensslの環境設定を行った

```
$ brew info openssl
で表示される環境変数全部追加
```

**Comment by niceonionslice** [comment]
Gemfileをもとに戻して
$ rm -rf ./vendor/bundleしてから以下を実行

```
$ bin/bundle install --path ./vendor/bundle
```

迷走。。

ダメだった。
インストールするバージョンがダメなのかもしれない。

![image](https://user-images.githubusercontent.com/30763221/53698049-1478a200-3e1b-11e9-9137-f0d362d0d8be.png)

参考までに。
https://www.tmp1024.com/programming/rails-mysql2-version-error/

**Comment by niceonionslice** [comment]
環境を整理するために一旦怪しいところは全部削除していく

`brew uninstall mysql@5.7 mysql@5.6`

**Comment by niceonionslice** [comment]
https://qiita.com/ozin/items/03a300749040ae11da2a
こちらのサイトでmysql2で失敗する時にはbundle configをしなさいという記事を見つけた。

試しに対応してみたが改善できず。

**Comment by niceonionslice** [comment]
`bundle list` 以下のメッセージがでてきた。

Gems included by the bundle:
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Could not find mysql2-0.5.2 in any of the sources

**Comment by niceonionslice** [comment]
$ bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Writing lockfile to /Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/Gemfile.lock

**Comment by niceonionslice** [comment]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
だめですね。。

**Comment by niceonionslice** [comment]
`bin/rails about`で表示されるこのメッセージから解決を試みる。
`Could not find mysql2-0.5.2 in any of the sources`

**Comment by niceonionslice** [comment]
https://qiita.com/ffggss/items/2a6e965c8c3133a92eb9
↑起きている事象含めて似ている。

試してみたがやはり失敗

**Comment by niceonionslice** [comment]
しょうがないのでとりあえずgemfileからmysql2 をコメントアウトして
bundle installを実行してから
`bundle exec gem install mysql2 -- --with-cflags=\"-I/usr/local/opt/openssl/include\" --with-ldflags=\"-L/usr/local/opt/openssl/lib\"`を実施しました。

で以下のメッセージ
```
cat  /Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/vendor/bundle/ruby/2.5.0/extensions/x86_64-darwin-18/2.5.0-static/mysql2-0.5.2/gem_make.out
current directory: /Users/kojiro.yamashiro/Projects/private/taskleaf-sandbox/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/ext/mysql2
/Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/bin/ruby -I /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0 -r ./siteconf20190306-72385-1foj61n.rb extconf.rb --with-cflags\=\"-I/usr/local/opt/openssl/include\" --with-ldflags\=\"-L/usr/local/opt/openssl/lib\"
/Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/lockfile_parser.rb:95:in `initialize'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:83:in `new'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:83:in `initialize'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/dsl.rb:234:in `new'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/dsl.rb:234:in `to_definition'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/dsl.rb:13:in `evaluate'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:34:in `build'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:135:in `definition'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:101:in `setup'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/kojiro.yamashiro/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'

extconf failed, exit code 1
```

**Comment by niceonionslice** [comment]
👍 やっとできた。
結果としては mysql2 2.5.1をインストールすることは諦めた。
まず、Gemfileからmysql2をコメントアウトしてbundle installを実施。

gem 'mysql2', '~> 0.4.4' を追加して bundle install を実施する。
（この手順で一応 mysqlをインストールすることができた）

本来は 0.5.2 をインストールしないといけないのだが 解決できないので 0.4.10 がインストールされたことを確認した。

![image](https://user-images.githubusercontent.com/30763221/53841442-22c3eb00-3fe0-11e9-8186-5b291fa96d80.png)

🎊

**Comment by niceonionslice** [comment]
本命の`bcrypt`を無事にインストールすることができました。

![image](https://user-images.githubusercontent.com/30763221/53841593-7df5dd80-3fe0-11e9-9748-fa2b3d49d658.png)

💯

**Comment by niceonionslice** [comment]
完璧な解決方法はこれでした。
これ以外の余計なオプション情報は不要。
```
$ bundle config --local build.mysql2 --with-opt-dir="/usr/local/opt/openssl"
```
